import { describe, it, expect } from "vitest";
import { formatJsonReport, formatMarkdownReport, type JsonReport } from "./terminal.js";

describe("formatJsonReport", () => {
  it("creates report with findings and summary", () => {
    const findings = [
      {
        title: "Bug 1",
        description: "desc",
        severity: "major" as const,
        category: "bug" as const,
        stepsToReproduce: ["step1"],
        expected: "expected",
        actual: "actual",
      },
    ];
    const results = [
      { finding: findings[0], status: "created" as const, issueNumber: 42 },
    ];
    const report = formatJsonReport("acme/widget", findings, results, 5000);
    expect(report.repo).toBe("acme/widget");
    expect(report.summary.total).toBe(1);
    expect(report.summary.created).toBe(1);
    expect(report.elapsedMs).toBe(5000);
  });

  it("handles empty findings", () => {
    const report = formatJsonReport("acme/widget", [], [], 1000);
    expect(report.summary.total).toBe(0);
    expect(report.findings).toHaveLength(0);
  });
});

describe("formatMarkdownReport", () => {
  const baseReport: JsonReport = {
    repo: "acme/widget",
    findings: [
      {
        title: "Install fails",
        description: "npm install throws an error",
        severity: "critical",
        category: "installation",
        stepsToReproduce: ["Run npm install -g widget", "Observe error"],
        expected: "Successful install",
        actual: "ERESOLVE error",
      },
    ],
    results: [
      {
        finding: {
          title: "Install fails",
          description: "npm install throws an error",
          severity: "critical",
          category: "installation",
          stepsToReproduce: ["Run npm install -g widget"],
          expected: "Successful install",
          actual: "ERESOLVE error",
        },
        status: "created",
        issueNumber: 42,
      },
    ],
    summary: { total: 1, created: 1, skipped: 0, failed: 0 },
    elapsedMs: 5000,
  };

  it("includes repo name in title", () => {
    const md = formatMarkdownReport(baseReport);
    expect(md).toContain("# testme Report: acme/widget");
  });

  it("includes findings with severity", () => {
    const md = formatMarkdownReport(baseReport);
    expect(md).toContain("### CRITICAL: Install fails");
  });

  it("includes steps to reproduce", () => {
    const md = formatMarkdownReport(baseReport);
    expect(md).toContain("1. Run npm install -g widget");
  });

  it("includes issue summary table", () => {
    const md = formatMarkdownReport(baseReport);
    expect(md).toContain("#42");
    expect(md).toContain("created");
  });

  it("handles empty findings", () => {
    const empty: JsonReport = {
      repo: "acme/widget",
      findings: [],
      results: [],
      summary: { total: 0, created: 0, skipped: 0, failed: 0 },
    };
    const md = formatMarkdownReport(empty);
    expect(md).toContain("No issues found");
  });

  it("includes footer", () => {
    const md = formatMarkdownReport(baseReport);
    expect(md).toContain("Generated by [testme]");
  });
});
